CREATE TABLE [dbo].[USERS]
(
	[Id] INT PRIMARY KEY IDENTITY(1, 1),
	[Username] VARCHAR (255) NULL,
	[Password] VARCHAR (255) NULL,
	Date_Create DATE NULL
)

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'USERS';
SELECT * FROM USERS